### ISSUE TITLE
Redirect URL from old PDF sample to http://fakenews.publicdatalab.org

### ISSUE THREAD

**Issue by jwyg** [PublicDataLab/fake-news-field-guide#10]
Several publications have included the link to the sample of the field guide: https://fakenews.publicdatalab.org/download/SAMPLE-field-guide-to-fake-news.pdf 

At some point it would be good to redirect this to: https://fakenews.publicdatalab.org/

I gather this may be possible through editing the .htaccess file.

**Comment by mikima** [comment]
Issue related to the website https://github.com/PublicDataLab/fake-news-website

fixed it
