### ISSUE TITLE
Wrong colour in graphic 2-1-c

### ISSUE THREAD

**Issue by jwyg** [PublicDataLab/fake-news-field-guide#12]
We think we've spotted an error in graphic 2-1-c..

The two earliest stories (in Feb 2016) are marked orange, which the legend says means they are "fake news".

According to the data where they have been coded, it says they are not "debunking" the "fake story" (which is correct), but it also does not classify them as "fake news". Revisiting the stories it is clear that they are discussing the Pope's views about Trump prior to the "fake news" story that "Pope endorses Trump":

https://www.commonwealmagazine.org/blog/no-pope-francis-nothing-donald-trump
https://www.thedailybeast.com/did-pope-francis-just-sink-trump

Either we could introduce a third classification (neither "fake news" nor "debunking" - e.g. we could grey them out), or remove them from the graphic (assuming that the items in this graphic are filtered).

@tommv - do you have any thoughts on this (as you were part of the group that worked on this)?

**Comment by mikima** [comment]
Ok so they are referring to another story, is it right?

In this case i think we should remove them and therefore rescale the whole graphic.

What do you think?

**Comment by angelesbri1s** [comment]
done!
