### ISSUE TITLE
Direct download URL for field guide?

### ISSUE THREAD

**Issue by jwyg** [PublicDataLab/fake-news-field-guide#8]
We've been asked: what is the best direct download URL for the field guide on Github?

When browsing the repo, it looks like this (but the PDF does not always seem to load correctly in the browser, perhaps due to its size?):
https://github.com/PublicDataLab/fake-news-field-guide/blob/master/output/A%20Field%20Guide%20to%20Fake%20News.pdf

Perhaps better would be the link from the download button on that page?
https://github.com/PublicDataLab/fake-news-field-guide/raw/master/output/A%20Field%20Guide%20to%20Fake%20News.pdf

Are either of these persistent links that we can share externally (assuming the file name does not change), even if we make changes to the PDF? Or will these links break? I'd assume the former?

**Comment by mikima** [comment]
Why should we provide a direct download link? I'd share the fake news website and from there the user can download the guide. it's one more click but i'm more confident that the website url won't change rather than the github url.

**Comment by jwyg** [comment]
I think the reason was social sharing (so people can link directly to the PDF), and possibly also search engine indexing (like [this](https://imgur.com/T4Gziwk)).

But let's stick with the website URL -  and then we can focus on a single link! 👍

**Comment by mikima** [comment]
I see. What about using zenodo (https://zenodo.org) to make a release? it owuld also provide a DOI to our publication

**Comment by mikima** [comment]
Anyway to answer to the original question, here you can find the first version of the guide:
https://github.com/PublicDataLab/fake-news-field-guide/releases/download/1.0.0/A_Field_Guide_to_Fake_News_and_other_Information_Disorders-single_pages.pdf

i would share this link.

**Comment by jwyg** [comment]
Perfect!

DOI here: https://doi.org/10.5281/zenodo.1136271

Closing this issue. :blush:
